const movies = [
  {
    _id: "1rsr",
    title: "Terminator",
    genre: { _id: "Action", name: "Action" },
    numberInStock: 5,
    dailyRentalRate: 2.7,
    publishedDate: 2019,
    liked: true,
  },
  {
    _id: "1srssr",
    title: "Die Hard",
    genre: { _id: "33eedbvb", name: "Action" },
    numberInStock: 5,
    dailyRentalRate: 2.7,
    publishedDate: 2019,
    liked: false,
  },
  {
    _id: "1rwwrrr",
    title: "Die Small",
    genre: { _id: "33eedbvb", name: "Action" },
    numberInStock: 5,
    dailyRentalRate: 2.7,
    publishedDate: 2020,
    liked: true,
  },
  {
    _id: "1rrsssxsss",
    title: "ipupa",
    genre: { _id: "33eedbvb", name: "Action" },
    numberInStock: 225,
    dailyRentalRate: 2.7,
    publishedDate: 2020,
    liked: false,
  },
  {
    _id: "1rreeessdds",
    title: "ipupa",
    genre: { _id: "33eedbvb", name: "Action" },
    numberInStock: 5,
    dailyRentalRate: 2.7,
    publishedDate: 2020,
    liked: false,
  },
  {
    _id: "1rrsqseeesss",
    title: "ipupa",
    genre: { _id: "33eedbvb", name: "Action" },
    numberInStock: 5,
    dailyRentalRate: 2.7,
    publishedDate: 2020,
    liked: false,
  },
  {
    _id: "pppscddc",
    title: "ipupa",
    genre: { _id: "33eedbvb", name: "Action" },
    numberInStock: 1,
    dailyRentalRate: 2.7,
    publishedDate: 2020,
    liked: false,
  },
  {
    _id: "wwwdlc",
    title: "ipupa",
    genre: { _id: "33eedbvb", name: "Action" },
    numberInStock: 9,
    dailyRentalRate: 2.7,
    publishedDate: 2020,
    liked: false,
  },
  {
    _id: "aqwedcpccv",
    title: "ipupa",
    genre: { _id: "33eedbvb", name: "Action" },
    numberInStock: 1,
    dailyRentalRate: 2.7,
    publishedDate: 2020,
    liked: false,
  },
  {
    _id: "aqwesdcccvdd",
    title: "ipupa",
    genre: { _id: "33eedbvb", name: "Comedy" },
    numberInStock: 2,
    dailyRentalRate: 2.7,
    publishedDate: 2020,
    liked: false,
  },
  {
    _id: "aqwedceccavdd",
    title: "ipupa",
    genre: { _id: "33eedbvb", name: "Thriller" },
    numberInStock: 25,
    dailyRentalRate: 2.7,
    publishedDate: 2020,
    liked: false,
  },
];
export const getMovies = () => {
  return movies;
};
export default movies;
