const movies = [
  {
    _id: "1rsr",
    title: "Terminator",
    genre: { _id: "Action", name: "Action" },
    numberInStock: 5,
    dailyRentalRate: 2.7,
    publishedDate: 2019,
    liked: true,
  },
  {
    _id: "1srsr",
    title: "Die Hard",
    genre: { _id: "33eedbvb", name: "Action" },
    numberInStock: 5,
    dailyRentalRate: 2.7,
    publishedDate: 2019,
    liked: false,
  },
  {
    _id: "1rrrr",
    title: "Die Small",
    genre: { _id: "33eedbvb", name: "Action" },
    numberInStock: 5,
    dailyRentalRate: 2.7,
    publishedDate: 2020,
    liked: true,
  },
  {
    _id: "1rrsss",
    title: "ipupa",
    genre: { _id: "33eedbvb", name: "Action" },
    numberInStock: 225,
    dailyRentalRate: 2.7,
    publishedDate: 2020,
    liked: false,
  },
  {
    _id: "1rreeesss",
    title: "ipupa",
    genre: { _id: "33eedbvb", name: "Action" },
    numberInStock: 5,
    dailyRentalRate: 2.7,
    publishedDate: 2020,
    liked: false,
  },
  {
    _id: "1rrsseeesss",
    title: "ipupa",
    genre: { _id: "33eedbvb", name: "Action" },
    numberInStock: 5,
    dailyRentalRate: 2.7,
    publishedDate: 2020,
    liked: false,
  },
  {
    _id: "pppsddc",
    title: "ipupa",
    genre: { _id: "33eedbvb", name: "Action" },
    numberInStock: 1,
    dailyRentalRate: 2.7,
    publishedDate: 2020,
    liked: false,
  },
  {
    _id: "wwwdc",
    title: "ipupa",
    genre: { _id: "33eedbvb", name: "Action" },
    numberInStock: 9,
    dailyRentalRate: 2.7,
    publishedDate: 2020,
    liked: false,
  },
  {
    _id: "aqwedcccv",
    title: "ipupa",
    genre: { _id: "33eedbvb", name: "Action" },
    numberInStock: 1,
    dailyRentalRate: 2.7,
    publishedDate: 2020,
    liked: false,
  },
  {
    _id: "aqwedcccvdd",
    title: "ipupa",
    genre: { _id: "33eedbvb", name: "Comedy" },
    numberInStock: 2,
    dailyRentalRate: 2.7,
    publishedDate: 2020,
    liked: false,
  },
  {
    _id: "aqwedceccvdd",
    title: "ipupa",
    genre: { _id: "33eedbvb", name: "Thriller" },
    numberInStock: 25,
    dailyRentalRate: 2.7,
    publishedDate: 2020,
    liked: false,
  },
];
export const getMovies = () => {
  return movies;
};
export default movies;
